;;; -*- Mode: LISP; Syntax: Common-Lisp; Package: USER; Base: 10 -*-
(defun load-9g-disk ()
  (SI:COM-ENABLE-SERVICES ':ALL)
  (SI:COM-LOAD-FILE '(#P"FEP0:>patches>fepfs-patch.ibin.4"))
  (SI:COM-LOAD-FILE '(#P"FEP0:>patches>copy-world-patch.ibin.2"))
  (STORAGE::COM-CREATE-INITIAL-FEP-FILESYSTEM '3)
  (STORAGE::COM-CREATE-INITIAL-FEP-FILESYSTEM '4)
  (STORAGE::COM-CREATE-INITIAL-FEP-FILESYSTEM '5)
  (WORLD-TOOLS:COM-COPY-WORLD '(#P"FEP0:>i328*.*.*") '#P"FEP3:>*.*.*")
  (WORLD-TOOLS:COM-CREATE-FEP-FILE '#P"FEP3:>page.page.newest" '500000)
  (WORLD-TOOLS:COM-CREATE-FEP-FILE '#P"FEP3:>page.page.newest" '500000)
  (WORLD-TOOLS:COM-COPY-WORLD '(#P"FEP0:>*.ilod.*") '#P"FEP3:>*.*.*")
  (SI:COM-COPY-FILE '(#P"FEP0:>patches>*.*.*") '#P"FEP3:>patches>*.*.*" ':CREATE-DIRECTORIES ':YES)
  (SI:COM-COPY-FILE '(#P"FEP0:>Boot.boot.1" #P"FEP0:>Hello.boot.1" #P"FEP0:>Local.boot.1" #P"FEP0:>fspt.fspt.1") '#P"FEP3:>*.*.*")
  (loop for file in (directory "fep3:>*.*.*")
    do (fs::change-file-properties file t :dont-delete t))
  (loop for file in (directory "fep3:>patches>*.*.*")
    do (fs::change-file-properties file t :dont-delete t))
  (WORLD-TOOLS:COM-COPY-WORLD '(#P"FEP1:>lmfs.file.1") '#P"FEP4:>*.*.*")
  (SI:COM-SHOW-DIRECTORY '(#P"FEP3:>*.*.*"))
  (WORLD-TOOLS:COM-EDIT-DISK-LABEL '3)
)
